const MenuItems = [
    // Veg
    {
        id: 0,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Sahi Paneer",
        description: "Try Our Delicious Sahi Paneer in just $20 our sahi paneer is one of the best item of our Royal Hotel",
    },
    {
        id: 1,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Pasta Primavera",
        description: "A vibrant and fresh dish featuring seasonal vegetables tossed with pasta in a light and flavorful sauce",
    },
    {
        id: 2,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/17012846/pexels-photo-17012846/free-photo-of-roasted-fish-on-plate.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Garlic Bread",
        description: "A mouthwatering classic, with freshly baked bread slathered in garlic butter, toasted to perfection, and served warm.",
    },
    {
        id: 3,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/1269665/pexels-photo-1269665.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Burger",
        description: " A delicious handheld meal with a juicy patty, fresh toppings, and a toasted bun, perfect for satisfying cravings",
    },
    {
        id: 4,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/6599106/pexels-photo-6599106.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Daal Makhni",
        description: "A rich and creamy lentil dish made with black lentils, kidney beans, butter, and aromatic spices, simmered to perfection.",
    },
    {
        id: 5,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Samosa",
        description: "A popular Indian snack with a crispy pastry shell filled with savory spiced potatoes, peas, and sometimes Pasta.",
    },
    {
        id: 6,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/1600711/pexels-photo-1600711.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Sandwich",
        description: "A versatile and satisfying meal, made with layers of bread filled with various ingredients like meats, vegetables, and spreads",
    },
    {
        id: 7,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Chow Mein",
        description: "A flavorful Chinese stir-fried noodle dish with a mix of vegetables, protein (such as chicken or shrimp), and savory sauces.",
    },
    {
        id: 8,
        category: "veg",
        mainImage: "https://images.pexels.com/photos/7340936/pexels-photo-7340936.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Jeera Rice",
        description: "Fragrant basmati rice cooked with cumin seeds and aromatic spices, resulting in a flavorful and aromatic side dish.",
    },
    // Non-Veg
    {
        id: 9,
        category: "nonveg",
        mainImage: "https://images.pexels.com/photos/12118979/pexels-photo-12118979.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Chicken French Fries",
        description: "Crispy and seasoned French fries served with tender and flavorful chicken strips, perfect for a tasty snack or meal.",
    },
    
    {
        id: 10,
        category: "nonveg",
        mainImage: "https://images.pexels.com/photos/12842265/pexels-photo-12842265.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Chicken Biryani",
        description: "A fragrant and flavorful rice dish made with basmati rice, succulent chicken, aromatic spices, and caramelized onions",
    },
    
    {
        id: 11,
        category: "nonveg",
        mainImage: "https://images.pexels.com/photos/2569760/pexels-photo-2569760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Creamy Chicken",
        description: "Tender chicken cooked in a luscious and creamy sauce, often infused with herbs, garlic, and a touch of richness",
    },
    {
        id: 12,
        category: "nonveg",
        mainImage: "https://images.pexels.com/photos/2015191/pexels-photo-2015191.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Chicken Roll",
        description: "A delicious handheld snack or meal, featuring succulent chicken wrapped in a soft flatbread with fresh vegetables and sauces",
    },
    {
        id: 13,
        category: "nonveg",
        mainImage: "https://images.pexels.com/photos/929137/pexels-photo-929137.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Mutton Puff",
        description: "Flaky puff pastry filled with tender mutton and aromatic spices, creating a savory treat that's both crispy and flavorful.",
    },
    {
        id: 14,
        category: "nonveg",
        mainImage: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Mutton Burger",
        description: "Juicy mutton patty infused with spices, topped with fresh lettuce, tomato, and tangy sauce, served in a soft bun.",
    },
    {
        id: 15,
        category: "nonveg",
        mainImage: "https://images.pexels.com/photos/792024/pexels-photo-792024.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Chicken Pakoda",
        description: "Crispy and flavorful chicken fritters, seasoned with aromatic spices, served with a zesty dipping sauce. Perfectly crispy and delicious.",
    },
     // Desert
     {
        id: 16,
        category: "desert",
        mainImage: "https://images.pexels.com/photos/10864158/pexels-photo-10864158.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Mushroom Cake",
        description: "A savory delight, our Mushroom Cake features a medley of earthy mushrooms baked into a moist and flavorful cake.",
    },
     {
        id: 17,
        category: "desert",
        mainImage: "https://images.pexels.com/photos/792024/pexels-photo-792024.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Chicken Pakoda",
        description: "Crispy and flavorful chicken fritters, seasoned with aromatic spices, served with a zesty dipping sauce. Perfectly crispy and delicious.",
    },
     {
        id: 18,
        category: "desert",
        mainImage: "https://images.pexels.com/photos/827513/pexels-photo-827513.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Cake With Berries",
        description: "Indulge in our exquisite cake layered with luscious berries, a symphony of sweet flavors and delightful textures. A berry lover's dream.",
    },
     {
        id: 19,
        category: "desert",
        mainImage: "https://images.pexels.com/photos/867452/pexels-photo-867452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Doughnut",
        description: "Enjoy the blissful simplicity of our fluffy and glazed doughnut, a classic treat that will satisfy your sweet cravings.",
    },
     {
        id: 20,
        category: "desert",
        mainImage: "https://images.pexels.com/photos/1752506/pexels-photo-1752506.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Ice Cream",
        description: "Delight in our creamy and indulgent ice cream, crafted with the finest ingredients for a refreshing and blissful dessert experience.",
    },
     {
        id: 21,
        category: "desert",
        mainImage: "https://images.pexels.com/photos/674584/pexels-photo-674584.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        heading: "Baked Bread",
        description: "Savor the irresistible aroma and warm goodness of our freshly baked bread, a crusty delight that pairs perfectly with any meal.",
    },
]
export default MenuItems;